name: packages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  conda_build_new:
    name: Build Conda New
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          environments: "build-new"
      - run: pixi run -e build-new build-conda
  conda_build_old:
    name: Build Conda Old
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          environments: "build-old"
      - run: pixi run -e build-old build-conda
